#!/bin/sh

node  /scripts/JD_DailyBonus.js
node  /scripts/index.js
node  /scripts/jd_bean_change.js
node  /scripts/jd_bean_home.js
node  /scripts/jd_bean_sign.js
node  /scripts/jd_beauty.js
node  /scripts/jd_blueCoin.js
node  /scripts/jd_bookshop.js
node  /scripts/jd_car.js
node  /scripts/jd_car_exchange.js
node  /scripts/jd_cash.js
node  /scripts/jd_cfd.js
node  /scripts/jd_club_lottery.js
node  /scripts/jd_crazy_joy.js
node  /scripts/jd_daily_egg.js
node  /scripts/jd_delCoupon.js
node  /scripts/jd_dreamFactory.js
node  /scripts/jd_family.js
node  /scripts/jd_fruit.js
node  /scripts/jd_health.js
node  /scripts/jd_jdfactory.js
node  /scripts/jd_jdzz.js
node  /scripts/jd_joy.js
node  /scripts/jd_joy_feedPets.js
node  /scripts/jd_joy_help.js
node  /scripts/jd_joy_reward.js
node  /scripts/jd_joy_run.js
node  /scripts/jd_joy_steal.js
node  /scripts/jd_jxd.js
node  /scripts/jd_jxnc.js
node  /scripts/jd_kd.js
node  /scripts/jd_live.js
node  /scripts/jd_live_redrain.js
node  /scripts/jd_lotteryMachine.js
node  /scripts/jd_mohe.js
node  /scripts/jd_moneyTree.js
node  /scripts/jd_ms.js
node  /scripts/jd_necklace.js
node  /scripts/jd_nzmh.js
node  /scripts/jd_pet.js
node  /scripts/jd_pigPet.js
node  /scripts/jd_plantBean.js
node  /scripts/jd_price.js
node  /scripts/jd_rankingList.js
node  /scripts/jd_redPacket.js
node  /scripts/jd_sgmh.js
node  /scripts/jd_shop.js
node  /scripts/jd_small_home.js
node  /scripts/jd_speed.js
node  /scripts/jd_speed_redpocke.js
node  /scripts/jd_speed_sign.js
node  /scripts/jd_superMarket.js
node  /scripts/jd_syj.js
node  /scripts/jd_unsubscribe.js
node  /scripts/jx_sign.js
node  /scripts/tencentscf.js
